name: 再试试
on:
   workflow_dispatch:
jobs:
   Atry:
      runs-on: ubuntu-latest
      steps:
         - name: 试一下
           uses: actions/checkout@v2
         - name: 输出有什么
           run: ls
         - name: 尝试输出文件
           uses: actions/upload-artifact@v2
           with:
             name: script.py
             path: script.py
